import "./globals.css";
import Footer from "./component/Footer";
import Navbar from "./component/Navbar";
import { Inter } from "next/font/google";

export const metadata = {
  title: "dotcam.ca",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${inter.className} bg-black pl-0 md:pl-[75px]`}>
        <Navbar />
        <div className="mt-10 md:mt-0"></div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
