import "./globals.css";
import Footer from "./component/Footer";
import Navbar from "./component/Navbar";
import { Inter } from "next/font/google";
import InnerLayout from "./InnerLayout";

export const metadata = {
  title: "dotcam.ca",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Chonburi&display=swap" rel="stylesheet"></link>

      </head>
      <body className={`${inter.className} `}>
       <InnerLayout>

        {children}
       </InnerLayout>
      </body>
    </html>
  );
}
